# Generated by Django 5.2.1 on 2025-06-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_mobile', models.CharField(max_length=50)),
                ('user_bussiness', models.CharField(max_length=50)),
            ],
        ),
    ]
