# Generated by Django 5.2.1 on 2025-06-05 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_title', models.CharField(max_length=50)),
                ('type_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogsTable',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('blog_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogtype')),
            ],
        ),
    ]
