# Generated by Django 5.2.1 on 2025-06-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogtype_type_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogstable',
            name='blog_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
